### ISSUE TITLE
ugly jpg

### ISSUE THREAD

**Issue by g-i-o-r-g-i-o** [Praful/vim-cheatsheet#1]
Can you please provide a jpeg version of higher quality? It clearly shows compression artifacts, and the border at the bottom looks very ugly.

**Comment by duilioisola** [comment]
There is a PDF to download. It has two pages. You can resize it as much as you want.
The jpeg is just a crop of the first page.

**Comment by g-i-o-r-g-i-o** [comment]
I know, thanks, but creating a jpg, resizing and optimizing it isn't always simple when you don't have an administrator account.

**Comment by Praful** [comment]
@GianniGi - As @duilioisola said, the jpg in the readme is just a "stylised" crop of the first page. It's aesthetic and not for use! 

I'm sorry I don't want to provide jpg versions of the cheatsheet because the next request from someone will probably be to provide different resolution images. Then I'll be creating a pdf and images from the Word file.

On Windows, copying the screen then pasting it into Paint can be done by normal (non-admin) users. There's probably an equivalent on Linux and macOS. There are also services and apps on the web that will convert PDF to JPG.

**Comment by g-i-o-r-g-i-o** [comment]
No way

Il giorno lunedì 20 maggio 2019, Praful <notifications@github.com> ha
scritto:
